### ISSUE TITLE
the dict_phone2vn.txt is already on the tts-web-demo folder

### ISSUE THREAD

**Issue by CrazyPlaysHD** [cuongnguyengit/tts-web-demo#1]
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from text2speech import T2S
  File "C:\Users\SS\Desktop\tts-web-demo-main\text2speech.py", line 14, in <module>
    from G2p import G2p
  File "C:\Users\SS\Desktop\tts-web-demo-main\G2p.py", line 2, in <module>
    from g2p_function import word2p
  File "C:\Users\SS\Desktop\tts-web-demo-main\g2p_function.py", line 5, in <module>
    with open(os.path.join(hp.checkpoint_path, 'dict_phone2vn.txt'), 'r', encoding='utf-8') as rf:
FileNotFoundError: [Errno 2] No such file or directory: '/content/tts-web-demo/dict_phone2vn.txt'

**Comment by cuongnguyengit** [comment]
They will update soon for new version.
Thanks.
